### ISSUE TITLE
Add link to reference or tutorial in "Welcome" screen

### ISSUE THREAD

**Issue by Potherca** [SimplyEdit/simplycode-docker#12]
The "Welcome" screen on first load  (before the first save has been created) should have a link to a reference or tutorial.

To take a new user by the hand, this could be part of an "Unsure what to build?" suggestion.  

https://github.com/SimplyEdit/simplycode-docker/blob/cefb0d193e116fc31a91b14854f8d0a09e508c33/403.php#L84-L91

**Comment by Hoxolotl** [comment]
Made a branch, added link and explanation
waiting for merge.

**Comment by Potherca** [comment]
Branch reviewed, waiting for change.

**Comment by Hoxolotl** [comment]
Change made
