### ISSUE TITLE
arm64 platform support missing

### ISSUE THREAD

**Issue by Hoxolotl** [SimplyEdit/simplycode-docker#8]
When trying to run the following command on an Apple M1-pro laptop under macos:

```sh
docker pull ghcr.io/simplyedit/simplycode-docker:main docker run --interactive --rm --tty \
  --volume "${PWD}:/var/www/www/api/data" \ 
  ghcr.io/simplyedit/simplycode-docker:main
```

Gives the result:

> Status: Image is up to date for ghcr.io/simplyedit/simplycode-docker:main ghcr.io/simplyedit/simplycode-docker:main WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested Please call this docker image with --env "USER_ID=$(id -u)" --env "USER_GID=$(id -g)" There does not seem to be a "generated.html" file. If you have not yet saved your application, this is expected. Otherwise, this might indicate a problem with the volume mount.

Please implement support for platform, thank you!

**Comment by Potherca** [comment]
A first attempt to support ARM64 has been made in #9 

If all went well, this docker image _should_ also work on MacOS / ARM achitecture:

```sh
docker pull ghcr.io/simplyedit/simplycode-docker:9_merge
docker run \
    --env "USER_GID=$(id -g)" \
    --env "USER_ID=$(id -u)" \
    --interactive \
    --rm \
    --tty \
    --publish-all \
    --volume "${PWD}:/var/www/www/api/data" \
    ghcr.io/simplyedit/simplycode-docker:9_merge
```

@Hoxolotl Could you try and report success/failure?
